# Pipeline from https://playwright.dev/docs/ci#bitbucket-pipelines

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: PowerAppConfig

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: npm ci
    displayName: "npm clean install"

  - script: npx playwright install --with-deps
    displayName: "Install Playwright and browsers"

  - script: export USERNAME=$(USERNAME) PASSWORD=$(PASSWORD) SECRET=$(SECRET) APP_ID=$(APP_ID) COPILOT_ENABLED=$(COPILOT_ENABLED)   #variables added to DevOps at Pipelines > Library with above variable group name 
    displayName: "Export environment variables for use in the test"

  - script: npx playwright test --project=Chrome
    displayName: "Run the main test project"
    env:
      CI: "true"
      USERNAME: $(USERNAME)
      PASSWORD: $(PASSWORD)
      SECRET: $(SECRET)
      APP_ID: $(APP_ID)
      COPILOT_ENABLED: $(COPILOT_ENABLED)


  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      searchFolder: "test-results"
      testResultsFormat: "JUnit"
      testResultsFiles: "e2e-junit-results.xml"
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: "All tests"
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: playwright-report
      artifact: playwright-report
      publishLocation: "pipeline"
    condition: succeededOrFailed()
